// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RagAgentApi.Migrations
{
    [DbContext(typeof(RagAgentApi.Data.RagDbContext))]
    [Migration("20261007120000_AddGraphRAGConcepts")]
    partial class AddGraphRAGConcepts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Concept", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");

                    b.Property<string>("Name").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");

                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");

                    b.Property<System.Text.Json.JsonDocument>("Metadata").HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name").IsUnique().HasDatabaseName("IX_Concepts_Name");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Relation", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");

                    b.Property<Guid>("SourceConceptId").HasColumnType("uuid");

                    b.Property<Guid>("TargetConceptId").HasColumnType("uuid");

                    b.Property<string>("RelationType").HasMaxLength(128).HasColumnType("character varying(128)");

                    b.Property<double>("Weight").HasColumnType("double precision");

                    b.Property<Guid?>("DocumentId").HasColumnType("uuid");

                    b.Property<System.Text.Json.JsonDocument>("Metadata").HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId").HasDatabaseName("IX_Relations_DocumentId");

                    b.HasIndex("SourceConceptId").HasDatabaseName("IX_Relations_SourceConceptId");

                    b.HasIndex("TargetConceptId").HasDatabaseName("IX_Relations_TargetConceptId");

                    b.HasIndex("SourceConceptId", "TargetConceptId").HasDatabaseName("IX_Relations_Source_Target");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Relation", b =>
                {
                    b.HasOne("RagAgentApi.Models.PostgreSQL.Concept", null)
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourceConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagAgentApi.Models.PostgreSQL.Concept", null)
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagAgentApi.Models.PostgreSQL.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
        }
    }
}
