// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RagAgentApi.Data;

#nullable disable

namespace RagAgentApi.Migrations
{
    [DbContext(typeof(RagDbContext))]
    partial class RagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("InputData")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Metrics")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("OutputData")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("IX_AgentExecutions_AgentName");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_AgentExecutions_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AgentExecutions_Status");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("IX_AgentExecutions_ThreadId");

                    b.ToTable("AgentExecutions");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.AgentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AgentPipeline")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Capabilities")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("ChunkerConfig")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<JsonDocument>("ScraperConfig")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AgentTypes_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_AgentTypes_Name");

                    b.ToTable("AgentTypes");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Conversations_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Conversations_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Conversations_UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ScrapingDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ScrapedAt")
                        .HasDatabaseName("IX_Documents_ScrapedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Documents_Status");

                    b.HasIndex("Url")
                        .HasDatabaseName("IX_Documents_Url");

                    b.HasIndex("UrlHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Documents_UrlHash");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ChunkMetadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("IX_DocumentChunks_Embedding_Cosine");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentChunks_DocumentId_ChunkIndex");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Vector>("QueryEmbedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<JsonDocument>("Sources")
                        .HasColumnType("jsonb");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_Messages_ConversationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Messages_CreatedAt");

                    b.HasIndex("QueryEmbedding")
                        .HasDatabaseName("IX_Messages_QueryEmbedding_Cosine");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("QueryEmbedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("QueryEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Messages_Role");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.UrlAgentMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentTypeId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UrlAgentMappings_IsActive");

                    b.HasIndex("Pattern")
                        .HasDatabaseName("IX_UrlAgentMappings_Pattern");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_UrlAgentMappings_Priority");

                    b.HasIndex("Pattern", "Priority")
                        .HasDatabaseName("IX_UrlAgentMappings_Pattern_Priority");

                    b.ToTable("UrlAgentMappings");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.AgentExecution", b =>
                {
                    b.HasOne("RagAgentApi.Models.PostgreSQL.AgentExecution", "ParentExecution")
                        .WithMany("ChildExecutions")
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentExecution");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.DocumentChunk", b =>
                {
                    b.HasOne("RagAgentApi.Models.PostgreSQL.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Message", b =>
                {
                    b.HasOne("RagAgentApi.Models.PostgreSQL.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.UrlAgentMapping", b =>
                {
                    b.HasOne("RagAgentApi.Models.PostgreSQL.AgentType", "AgentType")
                        .WithMany("UrlMappings")
                        .HasForeignKey("AgentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentType");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.AgentExecution", b =>
                {
                    b.Navigation("ChildExecutions");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.AgentType", b =>
                {
                    b.Navigation("UrlMappings");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("RagAgentApi.Models.PostgreSQL.Document", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
